[project]
name = "centipm"
version = "0.3.0-alpha.2"
description = "A compact, standalone environmental package manager."
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "requests>=2.32.5",
    "typer>=0.24.0",
]

[project.scripts]
centipm = "main:app"

[dependency-groups]
dev = [
    "pyinstaller>=6.19.0",
]
